config/routes.rb
Rails.application.routes.draw do
  root 'urls#new'

  get 'urls/new', to: 'urls#new', as: 'urls_new'
  post '/urls', to: 'urls#create', as: 'urls'
  get '/urls/:id', to: 'urls#show', as: 'url'
  get '/go/:random_string', to: 'urls#go', as: 'go'
end

#     root GET  /                   urls#new
# urls_new GET  /urls/new(.:format) urls#new
#     urls POST /urls(.:format)     urls#create
#      url GET  /urls/:id(.:format) urls#show

app/models/url.rb
class Url < ActiveRecord::Base
  validates :link, presence: true
  validates :random_string, presence: true, uniqueness: true
  has_many :visits
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def new
    @url = Url.new
  end

  def create 
    url = Url.create url_params
    url.random_string = SecureRandom.urlsafe_base64(6)
    if url.save
      redirect_to url
    else
      flash[:error] = "The url could not be saved. Try again"
      redirect_to root_path
    end
  end

  def show
    @url = Url.find(params[:id])
    @visits = @url.visits
  end

  def go
    url = Url.find_by(random_string: params[:random_string])
    if url
      url.visits.create
      redirect_to url.link
    else
      flash[:error] = "Sorry, ritly doesn't know that link"
      redirect_to root_path
    end
  end

  private 
    def url_params
      params.require(:url).permit(:link)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ritly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do|key,value| %>
	<div> <%=value%></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/urls/new.html.erb
<h1>Ritly</h1>

<%= form_for @url do |f| %>
  <%= f.label :link %>
  <%= f.text_field :link %>
  <%= f.submit %>
<% end %>

app/views/urls/show.html.erb
<%= link_to go_path(@url.random_string), go_path(@url.random_string) %> =>
<%= link_to @url.link, @url.link %>
<br>
<ul>
<% @visits.each do |visit| %>
  <li><%= visit.created_at %></li>
  <% end %>
</ul>